### ISSUE TITLE
Support OpenAPI example field

### ISSUE THREAD

**Issue by MihaiVoinea** [risen228/nestjs-zod#13]
Hello,

Is there any way to add the example property to the generated OpenAPI?

I'm interested to use this for DTOs. This is usually possible when declaring DTOs manually with the `ApiProperty` decorator, but I'm not sure how to do it when using `createZodDto`.

Thanks!

**Comment by ArtemKurtiakZenwayCode** [comment]
Hello, @MihaiVoinea @risenforces any updates on this?

**Comment by ArtemKurtiakZenwayCode** [comment]
I found possibility to add example and more metadata to property in zod-openapi:
https://github.com/anatine/zod-plugins/blob/main/packages/zod-openapi/README.md#extend-a-zod-schema-with-additional-openapi-schema-via-a-function-wrapper

I will be cool if it will be added to nestjs-zod

**Comment by MihaiVoinea** [comment]
I ended up switching to zod-openapi & zod-nestjs from @anatine for the time being. Those support this and other useful things.

**Comment by risenforces** [comment]
I won't add the same API, since it's very poorly designed. I'll try to find some better option and come back

**Comment by risenforces** [comment]
I think there may be an option to override all basic Zod types and add `example` property, but I assume it will have consequences.

**Comment by sankalpmukim** [comment]
Hi
Can we specify this in the README so people can judge the tradeoffs before committing to this option?

**Comment by GustavoOS** [comment]
@risen228 do you have any updates about this issue?
