### ISSUE TITLE
`createZodDto` doesnt generate openapi spec for param

### ISSUE THREAD

**Issue by Ubitso** [risen228/nestjs-zod#23]
I've tried to create dto for path param using `createZodDto` but it gives no openapi description for those class.
In example below I've showed one example without zod(it works fine) and extended by `createZodDto` class.

Here is reproduction example:
```typescript
import { Controller, Get, Param } from '@nestjs/common'
import { ApiProperty } from '@nestjs/swagger'
import { createZodDto } from 'nestjs-zod'
import { z } from 'nestjs-zod/z'

class SingleIdDto {
  @ApiProperty({ type: () => Number })
  id: number
}

export class SingleIdDto2 extends createZodDto(
  z.object({
    id: z.number().int().positive()
  })
) {}

@Controller('samples')
export class SampleController {
  @Get('/:id')
  async getHello(@Param() params: SingleIdDto2): Promise<any> {
    console.log({ params })

    return {}
  }
}

```

![image](https://user-images.githubusercontent.com/3361843/224276304-ed27dfd2-bfb3-4f21-8ac7-28561dc0d504.png)

**Comment by monisnap-julien** [comment]
Same issue here, seems to be working only for body params, but not for params, query and headers 👀

**Comment by risenforces** [comment]
I think the problem is that parameters and query require `@ApiProperty()` decorator on DTO's fields. Maybe we can solve this on patch level, but I'm not sure.

**Comment by ish-joshi** [comment]
I had the same issue, 

Temporary workaround was to basically add `ApiExtraModels` and `explode:true` properties. 

```typescript
@Get('/echo')
  @ApiOkResponse({
    description: 'Returns `Echo: <name>` indicating the service is functional',
  })
  @ApiExtraModels(EchoDto)
  @ApiQuery({
    required: true,
    name: 'queryParams',
    explode: true,
    type: 'object',
    schema: {
      $ref: getSchemaPath(EchoDto),
    },
  })
  getEcho(@Query() queryParams: EchoDto): string {
    return this.appService.getEcho(queryParams.folderName);
  }
```

**Comment by nicolabovolato** [comment]
I managed to solve this in a similar way. By getting the openAPI schema:

```ts
const query = z.object({
  limit: z.coerce.number().int().min(10).max(100),
  offset: z.coerce.number().int().min(0),
});
export const querySchema: SchemaObject = zodToOpenAPI(query);
``` 


I was able to to do this:

```ts
@Get()
  @ApiQuery({ name: 'offset', schema: querySchema.properties.offset })
  @ApiQuery({ name: 'limit', schema: querySchema.properties.limit })
  @ZodSerializerDto(ResponseDto)
  async getAll(@Query() { limit, offset }: QueryDto): Promise<Todo[]> {
    return await this.service.getAll(limit, offset);
  }
``` 

This way you end up with cleaner params:

![Screenshot 2023-05-21 at 18 59 51](https://github.com/risen228/nestjs-zod/assets/61934734/14ee596e-f294-4081-a2ba-2538952cea93)

And you can do the same for route params:

```ts
@Get(':id')
  @ApiParam({ name: 'id', schema: paramsSchema.properties.id })
  @ZodSerializerDto(ResponseDto)
  async getById(@Param() { id }: ParamsDto): Promise<Todo> {
    return await this.service.getById(id);
  }
```

![Screenshot 2023-05-21 at 19 04 46](https://github.com/risen228/nestjs-zod/assets/61934734/fd78f0f9-7687-4514-914e-51a6dd50f2ac)

**Comment by kinesias** [comment]
@anatine/zod-nestjs
This works.

**Comment by asifsaho** [comment]
call `patchNestJsSwagger` function before swagger document generation.

**Comment by taro-kayo** [comment]
[As suggested by the NestJS author](https://github.com/risen228/nestjs-zod/issues/65), we can use a static `_OPENAPI_METADATA_FACTORY` method to make it work for params and query.
This way there's no need to call `patchNestJsSwagger`. (This workaround may also work for https://github.com/risen228/nestjs-zod/issues/12.)

```typescript
import { Body, Controller, Get, Param, Query } from '@nestjs/common';
import { ApiOkResponse, ApiProperty } from '@nestjs/swagger';
import { SchemaObject } from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';
import { SchemaObjectMetadata } from '@nestjs/swagger/dist/interfaces/schema-object-metadata.interface';
import { zodToOpenAPI } from 'nestjs-zod';
import { z } from 'nestjs-zod/z';

// I'm not sure this is a complete transformation.
const toSchemaObjectMetadata = (schema: SchemaObject): SchemaObjectMetadata =>
  Object.fromEntries(
    Object.entries(schema.properties).map(([key, value]) => [
      key,
      {
        ...value,
        required: (schema.required ?? []).includes(key),
      },
    ]),
  );

const createZodClass = <T extends z.ZodObject<any>>(schema: T) => {
  return class {
    static _OPENAPI_METADATA_FACTORY = () =>
      toSchemaObjectMetadata(zodToOpenAPI(schema));
  };
};

class MyParam extends createZodClass(
  z.object({
    id: z.number().int().positive(),
  }),
) {
  @ApiProperty({ type: () => Number })
  id2: number;
}
class MyQuery extends createZodClass(
  z.object({
    key: z.string().uuid().optional().describe('foo'),
  }),
) {}
class MyBody extends createZodClass(
  z.object({
    key2: z.enum(['bar', 'baz']),
  }),
) {}
class MyRes extends createZodClass(
  z.object({
    key3: z.string().uuid().optional(),
    key4: z.array(z.string()),
  }),
) {}

@Controller()
export class AppController {
  @Get('/:id/:id2')
  @ApiOkResponse({ type: MyRes })
  root(
    @Param() params: MyParam,
    @Query() query: MyQuery,
    @Body() body: MyBody,
  ) {
    return 42;
  }
}
```

<img width="1231" alt="Screenshot 2023-11-23 at 16 21 26" src="https://github.com/risen228/nestjs-zod/assets/40859826/31c863ce-e9be-4b24-b3a9-79fa7b5beabc">

**Comment by fcl999** [comment]
> [正如 NestJS 作者所建议的那样](https://github.com/risen228/nestjs-zod/issues/65)，我们可以使用静态方法来使其适用于 params 和 query。这样就没有必要调用 .（此解决方法也可能适用于 #12。`_OPENAPI_METADATA_FACTORY``patchNestJsSwagger`
> 
> ```ts
> import { Body, Controller, Get, Param, Query } from '@nestjs/common';
> import { ApiOkResponse, ApiProperty } from '@nestjs/swagger';
> import { SchemaObject } from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';
> import { SchemaObjectMetadata } from '@nestjs/swagger/dist/interfaces/schema-object-metadata.interface';
> import { zodToOpenAPI } from 'nestjs-zod';
> import { z } from 'nestjs-zod/z';
> 
> // I'm not sure this is enough
> const toSchemaObjectMetadata = (schema: SchemaObject): SchemaObjectMetadata =>
>   Object.fromEntries(
>     Object.entries(schema.properties).map(([key, value]) => [
>       key,
>       {
>         ...value,
>         required: (schema.required ?? []).includes(key),
>       },
>     ]),
>   );
> 
> const createZodClass = <T extends z.ZodObject<any>>(schema: T) => {
>   return class {
>     static _OPENAPI_METADATA_FACTORY = () =>
>       toSchemaObjectMetadata(zodToOpenAPI(schema));
>   };
> };
> 
> class MyParam extends createZodClass(
>   z.object({
>     id: z.number().int().positive(),
>   }),
> ) {
>   @ApiProperty({ type: () => Number })
>   id2: number;
> }
> class MyQuery extends createZodClass(
>   z.object({
>     key: z.string().uuid().optional().describe('foo'),
>   }),
> ) {}
> class MyBody extends createZodClass(
>   z.object({
>     key2: z.enum(['bar', 'baz']),
>   }),
> ) {}
> class MyRes extends createZodClass(
>   z.object({
>     key3: z.string().uuid().optional(),
>     key4: z.array(z.string()),
>   }),
> ) {}
> 
> @Controller()
> export class AppController {
>   @Get('/:id/:id2')
>   @ApiOkResponse({ type: MyRes })
>   root(
>     @Param() params: MyParam,
>     @Query() query: MyQuery,
>     @Body() body: MyBody,
>   ) {
>     return 42;
>   }
> }
> ```
> 
> <img alt="Screenshot 2023-11-23 at 16 21 26" width="1231" src="https://private-user-images.githubusercontent.com/40859826/285123251-31c863ce-e9be-4b24-b3a9-79fa7b5beabc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNjc2MDAsIm5iZiI6MTcwMjA2NzMwMCwicGF0aCI6Ii80MDg1OTgyNi8yODUxMjMyNTEtMzFjODYzY2UtZTliZS00YjI0LWIzYTktNzlmYTdiNWJlYWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDIwMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYTljMWZjOTQyODcxMmUxYzJlNjc4MzUxOGZlNDY2NDJmY2RjOTQzNzMyZjY1Mzk1NjFhYTJhNjgxOThkNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kb0L3QndR4RBi9eVJrMotFwf0fDC1j4v15qnl9OzG8o">

Controller dto parameter is missing type and global validation pipeline is not working

**Comment by chriskuech** [comment]
I'm not sure why you would really want Param to use NestJS as it's more idiomatic to use the various Pipes just on that Param, ex: `@Param('myParam', ParseIntPipe) myParam: number`.

However, the lack of support for `@Query` is (IMO) a critical issue and we are currently keeping all our query DTOs as `class-transformer` until it's resolved.

**Comment by bekkazy-k** [comment]
I also encountered this problem. I wanted to switch from class-validator to zod, but this issue is quite significant for me.

**Comment by fcl999** [comment]
> I also encountered this problem. I wanted to switch from class-validator to zod, but this issue is quite significant for me.

```ts
import { ZodObject } from 'zod';
import { zodToOpenAPI } from 'nestjs-zod';
import { applyDecorators } from '@nestjs/common';
import { ApiQuery } from '@nestjs/swagger';

export const ApiQueryAll = (zodObject: ZodObject<any>) => {
  const openApi = zodToOpenAPI(zodObject);
  const decorators: MethodDecorator[] = [];
  if (typeof openApi.properties === 'object') {
    Object.entries(openApi.properties).forEach(([key, value]) => {
      decorators.push(
        ApiQuery({
          name: key,
          schema: value,
          required: (openApi.required ?? []).includes(key),
          description: 'description' in value ? value.description : '',
        }),
      );
    });
  }
  return applyDecorators(...decorators);
};


// controller
  @Get()
  @ApiOperation({ summary: '商品列表' })
  @ApiQueryAll(findItemDto)
  @ApiOkResponseData(ItemSchema, { isArray: true, isPager: true })
  findAll(
    @Query() dto: FindItemDto,
    @GetPayload() payload: Payload,
  ): Promise<Result<PaginatedDto<ItemSchema>>> {
    return this.service.findAll(payload.tenant!, dto);
  }


// dto
import { createZodDto } from 'nestjs-zod';
import { z } from 'zod';
import { bool, id, ids, page, pageSize } from '../../zod/type';

export const findItemDto = z.object({
  name: z.string().optional(),
  code: z.string().optional()),
  categoryIds: ids.optional(),
  isTemplate: bool.optional(),
  templateId: id.optional(),
  disable: bool.optional(),
  allowNegativeStock: bool.optional(),
  purchaseAllow: bool.optional(),
  salesAllow: bool.optional(),
  page: page,
  pageSize: pageSize,
});

export class FindItemDto extends createZodDto(findItemDto) {}

```

**Comment by bekkazy-k** [comment]
> > Я также столкнулся с этой проблемой. Я хотел перейти с класс-валидатора на зод, но для меня этот вопрос весьма существенен.
> 
> ```ts
> import { ZodObject } from 'zod';
> import { zodToOpenAPI } from 'nestjs-zod';
> import { applyDecorators } from '@nestjs/common';
> import { ApiQuery } from '@nestjs/swagger';
> 
> export const ApiQueryAll = (zodObject: ZodObject<any>) => {
>   const openApi = zodToOpenAPI(zodObject);
>   const decorators: MethodDecorator[] = [];
>   if (typeof openApi.properties === 'object') {
>     Object.entries(openApi.properties).forEach(([key, value]) => {
>       decorators.push(
>         ApiQuery({
>           name: key,
>           schema: value,
>           required: (openApi.required ?? []).includes(key),
>           description: 'description' in value ? value.description : '',
>         }),
>       );
>     });
>   }
>   return applyDecorators(...decorators);
> };
> 
> 
> // controller
>   @Get()
>   @ApiOperation({ summary: '商品列表' })
>   @ApiQueryAll(findItemDto)
>   @ApiOkResponseData(ItemSchema, { isArray: true, isPager: true })
>   findAll(
>     @Query() dto: FindItemDto,
>     @GetPayload() payload: Payload,
>   ): Promise<Result<PaginatedDto<ItemSchema>>> {
>     return this.service.findAll(payload.tenant!, dto);
>   }
> 
> 
> // dto
> import { createZodDto } from 'nestjs-zod';
> import { z } from 'zod';
> import { bool, id, ids, page, pageSize } from '../../zod/type';
> 
> export const findItemDto = z.object({
>   name: z.string().optional(),
>   code: z.string().optional()),
>   categoryIds: ids.optional(),
>   isTemplate: bool.optional(),
>   templateId: id.optional(),
>   disable: bool.optional(),
>   allowNegativeStock: bool.optional(),
>   purchaseAllow: bool.optional(),
>   salesAllow: bool.optional(),
>   page: page,
>   pageSize: pageSize,
> });
> 
> export class FindItemDto extends createZodDto(findItemDto) {}
> ```

What do ApiOkResponseData and GetPayload do? Can you send their code?

**Comment by fcl999** [comment]
> > > Я также столкнулся с этой проблемой. Я хотел перейти с класс-валидатора на зод, но для меня этот вопрос весьма существенен.
> > 
> > 
> > ```ts
> > import { ZodObject } from 'zod';
> > import { zodToOpenAPI } from 'nestjs-zod';
> > import { applyDecorators } from '@nestjs/common';
> > import { ApiQuery } from '@nestjs/swagger';
> > 
> > export const ApiQueryAll = (zodObject: ZodObject<any>) => {
> >   const openApi = zodToOpenAPI(zodObject);
> >   const decorators: MethodDecorator[] = [];
> >   if (typeof openApi.properties === 'object') {
> >     Object.entries(openApi.properties).forEach(([key, value]) => {
> >       decorators.push(
> >         ApiQuery({
> >           name: key,
> >           schema: value,
> >           required: (openApi.required ?? []).includes(key),
> >           description: 'description' in value ? value.description : '',
> >         }),
> >       );
> >     });
> >   }
> >   return applyDecorators(...decorators);
> > };
> > 
> > 
> > // controller
> >   @Get()
> >   @ApiOperation({ summary: '商品列表' })
> >   @ApiQueryAll(findItemDto)
> >   @ApiOkResponseData(ItemSchema, { isArray: true, isPager: true })
> >   findAll(
> >     @Query() dto: FindItemDto,
> >     @GetPayload() payload: Payload,
> >   ): Promise<Result<PaginatedDto<ItemSchema>>> {
> >     return this.service.findAll(payload.tenant!, dto);
> >   }
> > 
> > 
> > // dto
> > import { createZodDto } from 'nestjs-zod';
> > import { z } from 'zod';
> > import { bool, id, ids, page, pageSize } from '../../zod/type';
> > 
> > export const findItemDto = z.object({
> >   name: z.string().optional(),
> >   code: z.string().optional()),
> >   categoryIds: ids.optional(),
> >   isTemplate: bool.optional(),
> >   templateId: id.optional(),
> >   disable: bool.optional(),
> >   allowNegativeStock: bool.optional(),
> >   purchaseAllow: bool.optional(),
> >   salesAllow: bool.optional(),
> >   page: page,
> >   pageSize: pageSize,
> > });
> > 
> > export class FindItemDto extends createZodDto(findItemDto) {}
> > ```
> 
> What do ApiOkResponseData and GetPayload do? Can you send their code?

ApiOkResponseData is a custom response body decorator, and GetPayload is a decorator that obtains the tenant token in the request parameters. They have nothing to do with Query.

**Comment by GustavoOS** [comment]
I think this relates to #13

**Comment by Al-Ghoul** [comment]
What makes this completed? I think the issue persists

**Comment by piotracalski** [comment]
@BenLorantfy thanks for making that fix! I can confirm that, at least on my end, it solved above problem (query not visible in Swagger).
What is the timeline for v5 release?
