### ISSUE TITLE
Way to create DTO for output type of schema

### ISSUE THREAD

**Issue by falk-miracode** [risen228/nestjs-zod#26]
Is there a way to create a DTO for the transformed output type of schema?

Let's say, this is the schema for the DB model:

```TypeScript
const modelSchemaDb = z.object({
  id: z.string(),
  subItem: {
    id: z.string(),
    content: z.string(),
  },
})
```

In my API I want want the nested DB record to be flattened in the response, so I add a transform to the schema:

```TypeScript
const modelSchemaTransform = modelSchemaDb.transform((item) => ({
  id: item.id,
  content: item.subitem.content,
}))
```

Now I want to create a DTO class for the transformed output of the schema, but
```TypeScript
class modelDtoTransform extends createZodDto(modelSchemaTransform) {}
```
creates the same thing as
```TypeScript
class modelDtoDb extends createZodDto(modelSchemaDb) {}
```
A class matching the nested type:
```TypeScript
{
  id: string;
  subItem: {
    id: string;
    content: string;
  }
}
```
which leads to a wrong open api definition, in my case.

I need a DTO class matching the flattened type:
```TypeScript
{
  id: string;
  content: string;
}
```

Is there already a way to achive this?

**Comment by risenforces** [comment]
@falk-miracode Thanks for your question. I checked the examples, and I found that `modelDtoTransform` is not exactly the same thing as `modelDtoDb`:

- The inputs are the same for both DTOs (= `modelSchemaDb`). It means that validation fails if you pass "transformed" type to `modelDtoTransform` parameter. I don't think we can somehow fix it, because the transformed type doesn't have any schema - it's impossible to validate it in pipes, guards, etc. It just extracts your function's return type.
- The output is different:  `modelDtoTransform` used as a function parameter type produces `{ id: string; content: string }`, so here you get the "transformed" type. The `modelDtoDb` produces input type in this case.

So, you can use "transformed" DTO as a type, but not on controller level, since any validations will fail if you pass the transformed data there.

**Comment by falk-miracode** [comment]
@risenforces  Thanks for your response!

> @falk-miracode Thanks for your question. I checked the examples, and I found that `modelDtoTransform` is not exactly the same thing as `modelDtoDb`:
> 

Sorry, I expressed myself inaccurately. What I meant: `modelDtoTransform` produces the same (wrong) swagger document as `modelDtoDb`, when used as response type.

> […]
> * The output is different:  `modelDtoTransform` used as a function parameter type produces `{ id: string; content: string }`, so here you get the "transformed" type. The `modelDtoDb` produces input type in this case.
> 
> So, you can use "transformed" DTO as a type, but not on controller level, since any validations will fail if you pass the transformed data there.

Yes, the actual output is different. But, when used as output type, the DTO created from the transformed zod schema produces the same swagger doc as if I used a DTO created from the the untransformed zod schema.


This code reproduces my problem:

```TypeScript
import { ApiOkResponse } from "@nestjs/swagger"
import { Controller, Get } from "@nestjs/common"
import { createZodDto } from "nestjs-zod"
import { z } from "nestjs-zod/z"

/* eslint max-classes-per-file: ["error", 10] */

const modelSchemaDb = z.object({
    id: z.string(),
    subItem: z.object({
        id: z.string(),
        content: z.string(),
    }),
})

const modelSchemaTransform = modelSchemaDb.transform((item) => ({
    id: item.id,
    content: item.subItem.content,
}))

class modelDto extends createZodDto(modelSchemaTransform) {}

@Controller("test")
export default class TestController {
    @Get("/test")
    @ApiOkResponse({
        type: modelDto,
        description:
            "The latest version of the policy for the given policyType",
    })
    test() {
        return modelSchemaTransform.parse({
            id: "foo",
            subItem: {
                id: "bar",
                content: "baz",
            },
        })
    }
}
```

`/api`:
![image](https://user-images.githubusercontent.com/94826912/232787223-5490c71a-d4d5-4644-b90e-9841c9c9bf74.png)

The actual response (green) after execution does not match the documented response schema (red).

I assumed/hoped, that it's possible to derive the documentation for the response type from the transformed schema some how.

**Comment by lxia1220** [comment]
@falk-miracode it can be with [`.passthrough`](https://github.com/colinhacks/zod#passthrough).

**Comment by reztin** [comment]
I got the same issue. 

The created OpenAPI type from `createZodDto(myTransformZod)` does not care about the transformation. It takes the initial type without considering the transformation changes
