### ISSUE TITLE
Support extraction of inferred types – z.infer<typeof Schema>

### ISSUE THREAD

**Issue by falk-miracode** [risen228/nestjs-zod#27]
Please support the extraction of inferred types from schemas.

Original Zod supports the extraction of TypeScript types, which is very handy:

```TypeScript
import { z } from "zod";

const User = z.object({
  username: z.string(),
});

User.parse({ username: "Ludwig" });

// extract the inferred type
type User = z.infer<typeof User>;
// { username: string }
```
See: https://github.com/colinhacks/zod#basic-usage

In my current project I had to import original Zod for that use case only. I don't like that, because I'm afraid, that nestjs-zod's `createZodDto` on schemas created with original Zod may fail in the future due to compatibility issues. And it's also confusing for developers to have two variants of Zod in the same project.

**Comment by risenforces** [comment]
Now `zod` is a peer dependency, so you can safely use your `zod` instance. But yes, it's strange that `nestjs-zod/z` doesn't have `infer` inside, I'll check it

**Comment by Drago96** [comment]
@risen228 Any updates on this? I am currently facing the same issue.
