### ISSUE TITLE
throw error if validation pipe removes items from request

### ISSUE THREAD

**Issue by oldo** [risen228/nestjs-zod#40]
Hi there,
First up, loving the library and amazed it doesn't have more stars.
I have applied `ZodValidationPipe` globally and it's working a treat removing any unspecified properties from requests according to the request DTO. What I'd ideally like though is for an error to be thrown if a non whitelisted property is present in the request, rather than it just silently being stripped.
Is this possible?
Thanks :-)

**Comment by phaxz10** [comment]
I think you can just use `zodSchema.strict()` for this

**Comment by oldo** [comment]
Thanks @phaxz10 
Where do I apply this setting?
