### ISSUE TITLE
Created classes have properties marked as optional.

### ISSUE THREAD

**Issue by ngregrichardson** [risen228/nestjs-zod#47]
So I have a Zod schema `createAddressSchema` that works out to be the type below.

```ts
ZodObject<{name: ZodOptional<ZodNullable<ZodString>>, firstLine: ZodString}>
```

When I turn this into a class
```ts
import { createZodDto } from 'nestjs-zod';

export class NewAddress extends createZodDto(createAddressSchema) {}
```

However, looking at the properties on the generated class, every property is optional, even though `firstLine` should not be. Is there a reason for this?

```ts
{
    name?: string;
    firstLine?: string;
}
```

There is a chance it has to do with how I'm generating the Zod schema but since the type works out to not be wrapped in `ZodOptional` it seems like it should be fine.

Thanks!

**Comment by zeehjr** [comment]
Maybe you forgot to enable Typescript's strict mode?
https://www.typescriptlang.org/tsconfig#strict

**Comment by robertohein** [comment]
Same problem here, did you manage to resolve @ngregrichardson ?

**Comment by robertohein** [comment]
@ngregrichardson i've tryied adding strict true and did not work, but after changing my tsconfig.json strinctNullChecks to true it worked.
