### ISSUE TITLE
Support for async refinements

### ISSUE THREAD

**Issue by ItsaMeTuni** [risen228/nestjs-zod#51]
When using a `.refine` that returns a `Promise` I get the following error from Zod:

```
Async refinement encountered during synchronous parse operation. Use .parseAsync instead.
```

I assume `nestjs-zod` uses `.parse` under the hood. Is there a way to tell `nestjs-zod` to use `.parseAsync` instead?

**Comment by netojose** [comment]
I also would like to make some database verification, and should to be async validation. How to switch from .parse to .parseAsync?

**Comment by ropbastos** [comment]
I managed to have just that, I describe it here: https://github.com/anatine/zod-plugins/issues/34#issuecomment-1450823908

It would be nice to get proper support for that from one of those nestjs-zod projects though.
