### ISSUE TITLE
ZodSerializerInterceptor should return 500 instead of 400

### ISSUE THREAD

**Issue by nicolabovolato** [risen228/nestjs-zod#54]
I've registered ZodSerializerInterceptor as an APP_INTERCEPTOR in my root module.
It looks like that when a response object does not match what is defined in @ZodSerializerDto() a 400 error is returned, along with its error details.
I think that errors in response validation should return 500 instead, if the server doesn't return what it's supposed to that's a server error, isn't it?

**Comment by nicolabovolato** [comment]
@0rdep I agree with you, but here I'm talking about a response not respecting the api contract. What would happen if a response containing sensitive data gets to the client? Or one with a completely different format (perharps an object instead of an array of objects) gets through?
How would that be a client error?

[FastAPI](https://fastapi.tiangolo.com/tutorial/handling-errors/?h=500#requestvalidationerror-vs-validationerror) and [Fastify](https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/#serialization), to name a few, consider it a server side error. In some other languages and frameworks, with lack built-in validation, developers usually [second this decision](https://stackoverflow.com/questions/40034870/how-to-validate-web-api-response). 

I'll leave you with an excerpt from FastAPI's docs:
> RequestValidationError is a sub-class of Pydantic's [ValidationError](https://pydantic-docs.helpmanual.io/usage/models/#error-handling).
> FastAPI uses it so that, if you use a Pydantic model in response_model, and your data has an error, you will see the error in your log.
> But the client/user will not see it. Instead, the client will receive an "Internal Server Error" with a HTTP status code 500.
> It should be this way because if you have a Pydantic ValidationError in your response or anywhere in your code (not in the client's request), it's actually a bug in your code.
> And while you fix it, your clients/users shouldn't have access to internal information about the error, as that could expose a security vulnerability.

**Comment by 0rdep** [comment]
Hmm, yeah i see your point. I think in this case i agree with you that 500 makes more sense.
