### ISSUE TITLE
@ZodResponseDto decorator is missing

### ISSUE THREAD

**Issue by smolak** [risen228/nestjs-zod#57]
Hi

In the [README you mention to use the @ ZodResponseDto decorator](https://www.npmjs.com/package/nestjs-zod#user-content-use-zodresponsedto-to-define-the-shape-of-the-response-for-endpoint-in-controller), but it's nowhere to be found.
Where do I get it from?

**Comment by 0rdep** [comment]
I had the same issue, try ZodSerializerDto instead of ZodResponseDto

**Comment by smolak** [comment]
Thanks, will try it out and let people know here.
I don't want to decide, but either the docs need to be updated or the code.
