### ISSUE TITLE
Enum type issue

### ISSUE THREAD

**Issue by mohrazzak** [risen228/nestjs-zod#68]
Hello, I am using `Prisma` `Zod `and `nestjs-zod` and `nestjs-zod-prisma`
Which should be compitable with each others

I am generating the Zod schemas with `npx prisma generate` 
And everything goes well except for Role Enum 
`schema.prisma`
```
enum Role {
  USER
  STORE_OWNER
}
```
so when i run the `npx prisma generate` A Schema is generated based on my prisma table definitions 
`zod/storeowner.ts`
```ts
import { Role } from './enums';

export const StoreOwnerModel = z.object({
  role: z.nativeEnum(Role).default(Role.STORE_OWNER),
  // etc...
});
export class StoreOwnerEntity extends createZodDto(StoreOwnerModel) {}
```
`zod/enums.ts`
```ts
export enum Role {
  USER = "USER",
  STORE_OWNER = "STORE_OWNER"
}
```

When using the StoreOwnerEntity in my service it is giving `ts` error

`store-owner.service.ts`
```ts
  async findFirst(): Promise<StoreOwnerEntity | null> {
    return this.prismaService.storeOwner.findFirst();
  }
```
`Error`
```ts
Types of property 'role' are incompatible.
      Type 'import("c:/Users/saybers/Desktop/qbite/backend/node_modules/.prisma/client/index").$Enums.Role' is not assignable to type 'import("c:/Users/saybers/Desktop/qbite/backend/src/modules/zod/enums").Role'.
        Type '"USER"' is not assignable to type 'Role'.ts(2322)
```

**Comment by anton-series** [comment]
I believe it's because Prisma generates "fake" enums, which are really just an object. Don't have a solution though
