### ISSUE TITLE
Union type issue

### ISSUE THREAD

**Issue by capaio** [risen228/nestjs-zod#70]
When the schema contains a union I get an error:

`error TS2509: Base constructor return type [...] is not an object type or intersection of object types with statically known members`

example:
```
import { z } from 'nestjs-zod/z';

const unionTypeSchema = z.union([z.string(), z.number()]);
class Dto extends createZodDto(unionTypeSchema) {}
```

version: 3.0.0

**Comment by adamnyberg** [comment]
@capaio did you find a solution to this?

**Comment by Geebrox** [comment]
Any updates on this? Does this package support union types for Dtos?

**Comment by tjdammann** [comment]
Also seeing this issue when trying to generate a dto based on a discriminated union. Any advice/workarounds would be appreciated!

**Comment by tjdammann** [comment]
After digging a little more, was able to get it to work by wrapping the discriminated union in another object. For example, this does not work:

```
const schemaA = z.object({ ... });
const schemaB = z.object({ ... }); 
const unionSchema = z.discriminatedUnion("type", [schemaA, schemaB]);
class Dto extends createZodDto(unionSchema) {}
``` 

But this does work:

```
const schemaA = z.object({ ... });
const schemaB = z.object({ ... }); 
const unionSchema = z.discriminatedUnion("type", [schemaA, schemaB]);
const unionObjectSchema = z.object({ key: unionSchema });
class Dto extends createZodDto(unionObjectSchema) {}
``` 

Not sure if this is expected behavior or not.
