### ISSUE TITLE
Support setErrorMap

### ISSUE THREAD

**Issue by mohrazzak** [risen228/nestjs-zod#74]
Please Support setErrorMap from zod library

**Comment by GitAlison** [comment]
i need this to

**Comment by GitAlison** [comment]
i found this solution for the moment, check if works
`import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as i18next from 'i18next';
import { z } from 'zod';
import { makeZodI18nMap } from 'zod-i18n-map';
const translation = require('zod-i18n-map/locales/pt/zod.json')

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  await i18next.init({
    lng: "pt",
    resources: {
      pt: { zod: translation },
    },
  });

  z.setErrorMap(makeZodI18nMap(i18next));

  await app.listen(5555);
}
bootstrap();
`
