### ISSUE TITLE
Add support to `.brand` schemas

### ISSUE THREAD

**Issue by thawankeane** [risen228/nestjs-zod#75]
[Branded types](https://github.com/colinhacks/zod?tab=readme-ov-file#brand) in zod are very helpful in ensuring that a function argument or a value has been validated through a zod schema.

Today when using `.brand` in a schema, the `zodToOpenAPI` function doesn't generate the correct `type` at OpenAPI schema

**Comment by ubaldb** [comment]
Hi there,
I also stumbled upon this issue in our project. Branded types will just resolve to empty objects in the openAPI spec, which is a pity.
Afaik, it's really just three lines of production code to support branded types.

I would have opened a PR with a fix, but don't have the permissions.
Therefore, just posting a patch here:
 
[0001-fix-add-support-for-branded-zod-types.patch](https://github.com/risen228/nestjs-zod/files/14220250/0001-fix-add-support-for-branded-zod-types.patch)

I would be glad if one of the maintainers could take a look and add the support for branded types. 🙏
