### ISSUE TITLE
ZodDate does not generate type and format for OpenApi

### ISSUE THREAD

**Issue by lewinskimaciej** [risen228/nestjs-zod#82]
Hi,
so we're using nestjs-zod for a while an I'm trying to fix an issue we have with z.date() properties in our schemas. 
We have Prisma property of type DateTime, then we generate zod schemas via `zod-prisma` that end up being `z.coerce.date()` in models that we return from our API methods.
Turns out, if you use .date() approach, `nestjs-zod` will produce an empty `{}` object for all the properties with z.date() in OpenApi schemas: `"(...)createdAt":{},"updatedAt":{},(...)`
Sadly using `dateString()` doesn't work when the source is Date and we want a string output. Using just `z.date()` does work as it should, it just doesn't include type info. So essentially, we have a solution for parsing an input string into DateTime, but we lack a solution for actually parsing DateTime into string for output models.

This is quite important to us since we generate C# client based on OpenApi definition of our API and this ends up using `Object`, since specification doesn't have a type. It's annoying and less than ideal for our end-users.

There has been an exact same case in `zod-to-openapi` Pull Request: https://github.com/asteasolutions/zod-to-openapi/pull/183 which was refused. The issue is that `zod-to-openapi` actually has a solution to this since you can manually specify OpenApi params for every property, here - we can't.

There's few potential solutions I see here:
1. We do what mentioned PR assumed - just assign `type: 'string', format: 'date-time'` if type is `ZodDate` within `zod-to-openapi.ts` and be done, even if it sometimes might be just a `date` - less than ideal, but at least fixes most issues. Or at least assign `type: string` so it can be parsed properly by clients.
2. Introduce custom z.dateSomething() and z.dateTimeSomething() that would handle that specifically.
3. Expose a method like `zod-to-openapi`(`z.openapi()`) to customize OpenApi params on each type, I believe they use some tricks to get those into Zod types without specifically rewriting Zod. This is better and more flexible solution, potentially future-proof, but also quite complex to implement.

Let me know if I can do anything to help with this.

**Comment by GustavoOS** [comment]
I think this is related to #13
