### ISSUE TITLE
How do I show the validation errors when using a global pipe?

### ISSUE THREAD

**Issue by raedwa01** [risen228/nestjs-zod#83]
I implemented the code and used the global validation pipe.  The problem is, when validation fails, all that is returned is:
```
{
  "statusCode": 400,
  "message": "Validation failed"
}
```

I want to return the error array as well so the user knows what failed.  How do I include that in the response?

**Comment by stefaanMLB** [comment]
I have the same problem
After adding  @ZodSerializerDto(<dto>) I only get "Internal Server Error" without further explanation
That's very little to work with
