### ISSUE TITLE
ZodSerializerDto issue with array shape

### ISSUE THREAD

**Issue by lidmyr93** [risen228/nestjs-zod#89]
I'm having an issue serializing the following. Nestjs throws an 500 internal server error when using @ZodSerializerDto decorator but testing the Dto with **validate** gives the expected result (password & registerDate is stripped).

```javascript
const stuffThatNeedsToBeStripped =  [
      {
        id: 'd7197e2b-ab76-4889-8989-710b3253b6a6',
        status: 'PENDING',
        creator: {
          id: 'abb6eedf-2642-4ee9-851e-3d29e1d215d5',
          username: 'user1',
          password: 'PASSWORD',
          registerDate: '2024-02-22T09:14:14.698Z',
        },
      },
    ];

const Base = z.object({
  id: z.string(),
  status: z.string(),
  creator: z.object({ id: z.string(), username: z.string() }),
});

const ArrayOfBase = z.array(Base)

const ZodDto = createZodDto(ArrayOfBase)

 ```

[Reproduciton (Codesandbox)](https://codesandbox.io/p/devbox/affectionate-thunder-88fsf6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsyigf5b00073b6hzw46yfrc%2522%252C%2522sizes%2522%253A%255B58.72017353579176%252C41.27982646420824%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsyigf5b00023b6hksgm4xb8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsyigf5b00043b6hi9waksx0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsyigf5b00063b6h1g1zyzvj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsyigf5b00023b6hksgm4xb8%2522%253A%257B%2522id%2522%253A%2522clsyigf5b00023b6hksgm4xb8%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsyigf5b00063b6h1g1zyzvj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsyigf5b00053b6hg57m7v75%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clsyigf5b00063b6h1g1zyzvj%2522%252C%2522activeTabId%2522%253A%2522clsyigf5b00053b6hg57m7v75%2522%257D%252C%2522clsyigf5b00043b6hi9waksx0%2522%253A%257B%2522id%2522%253A%2522clsyigf5b00043b6hi9waksx0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsyigf5b00033b6hnbgkb9ns%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsyigf5b00033b6hnbgkb9ns%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Thanks in advance !

**Comment by DanielGiljam** [comment]
In the source you can see that it has special handling for responses that are arrays:

https://github.com/risen228/nestjs-zod/blob/d24982ed89fed5156d79dcc96b78079b04037e6c/src/serializer.ts#L38-L42

Basically, if what you're returning from a controller method is an array, then it'll validate each element in that array against your provided schema.

I got confused by that behavior at first as well... In my opinion, it would probably be better if that behavior would be removed from the library.

**Comment by lidmyr93** [comment]
Thanks for the reply ! 

Damn, I had that idea that it would work that way and I thought I tested it...

Yeah just defining the schema as below works.

```javascript
const Base = z.object({
  id: z.string(),
  status: z.string(),
  creator: z.object({ id: z.string(), username: z.string() }),
});

//const ArrayOfBase = z.array(Base);

const ZodDto = createZodDto(Base);

```

**Comment by lidmyr93** [comment]
Closing the issue and thanks !

**Comment by mallowigi** [comment]
@BenLorantfy can we reopen this and actually implement how it's supposed to work?

**Comment by maxijonson** [comment]
+1 on reopening this issue. I just stumbled on it too and was super confused because my controller correctly returned an array without the serializer, but then errors saying it got an object when I re-add the serializer...
