### ISSUE TITLE
Catch ZodSerializationException 

### ISSUE THREAD

**Issue by samuelpares** [risen228/nestjs-zod#92]
How can I catch ZodSerializationException?
When using serializer, if some error happens, it is not printed on console, neither returns to caller, making it hard to find out what is missing. Exempla: createdAt on schema is string and database returns date.
I could implement a AllExceptionFilter, but then I would loose all others default filters.

**Comment by snitsweb** [comment]
+1, I need to ZodSerializationException be exported from index.js file, because I'm catching exceptions from zod and depending on what exception it is I change my response.

**Comment by snitsweb** [comment]
I created a PR here: https://github.com/risen228/nestjs-zod/pull/93

**Comment by rhyek** [comment]
would appreciate a solution to this. exporting `ZodSerializationException` would be great. i'm currently having to do the following:
```typescript
@Catch()
export class AllExceptionsFilter extends BaseExceptionFilter {
  constructor(
    public readonly httpAdapterHost: HttpAdapterHost,
    private readonly logger: LoggerService,
  ) {
    const instance = httpAdapterHost.httpAdapter.getInstance();
    super(instance);
  }

  catch(exception: unknown, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<FastifyReply>();

    if (
      exception instanceof InternalServerErrorException &&
      exception.constructor.name === 'ZodSerializationException'
    ) {
      const zodError: ZodError = (exception as any).error;
      this.logger.error(
        zodError,
        'Failed to serialize response due to zod validation',
      );
      this.httpAdapterHost.httpAdapter.reply(
        response,
        exception.getResponse(),
        exception.getStatus(),
      );
      return;
    }
    super.catch(exception, host);
  }
}
```
