### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by GustavoOS** [risen228/nestjs-zod#94]
- Last released change was 8 months ago
- Number of issues rising (see how many issues relates to #13)
- Many issues the owner says will try to "find time" to develop
- Many issues unanswered for months

**Comment by ajfranzoia** [comment]
This project is clearly unmaintained. It would be good if the creator could add collaborators to it.

**Comment by GustavoOS** [comment]
> This project is clearly unmaintained. It would be good if the creator could add collaborators to it.

Or admit this unmaintenance and deprecate the npm package

**Comment by samuelpares** [comment]
> > This project is clearly unmaintained. It would be good if the creator could add collaborators to it.
> 
> Or admit this unmaintenance and deprecate the npm package

Yeah, I've adopted this package to share schemas and types in my mono repo application, and it's frustrating to see that it's been abandoned.

**Comment by GustavoOS** [comment]
@risen228 could you please deprecate this package at npm to avoid security flaws?

**Comment by BenLorantfy** [comment]
FYI @risen228 transferred the repo / npm package to myself and I un-deprecated it. I plan on maintaining it going forward starting with the suggestions here: https://github.com/BenLorantfy/nestjs-zod/issues/65

**Comment by lzw1926** [comment]
> FYI @risen228 transferred the repo / npm package to myself and I un-deprecated it. I plan on maintaining it going forward starting with the suggestions here: #65

What about [nestjs-zod-prisma](https://github.com/risen228/nestjs-zod-prisma), also maintained by @risen228

**Comment by BenLorantfy** [comment]
> > FYI @risen228 transferred the repo / npm package to myself and I un-deprecated it. I plan on maintaining it going forward starting with the suggestions here: #65
> 
> 
> 
> @BenLorantfy What about [nestjs-zod-prisma](https://github.com/risen228/nestjs-zod-prisma), also maintained by @risen228

https://github.com/BenLorantfy/nestjs-zod/issues/108#issuecomment-2440054407
